services:
  docker-port-manager:
    image: ghcr.io/bbv52021/docker-port-manager:latest
    container_name: docker-port-manager
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume1/docker/dpm/data:/app/data
    environment:
      - TZ=Asia/Shanghai
